DECLARE @startDate DATE SET @startDate = DATEADD(day, -2, GETDATE())
DECLARE @endDate DATE SET @endDate = DATEADD(day, -1, GETDATE())

SELECT DISTINCT
	SCS_STUDENT 'StudentID'
	,SEC_NAME, CAST(SEC_SHORT_TITLE AS VARCHAR(MAX)) AS 'SEC_SHORT_TITLE'
	,STC_START_DATE 'FromDate'
	,STC_END_DATE 'ToDate'
	,SEC_DEPTS
	,SEC_TERM
    ,STUDENT_COURSE_SEC_CHGDATE
FROM
	COURSE_SECTIONS
LEFT JOIN
	STUDENT_COURSE_SEC ON
	COURSE_SECTIONS.COURSE_SECTIONS_ID=STUDENT_COURSE_SEC.SCS_COURSE_SECTION
LEFT JOIN
	COURSES ON 
	SEC_COURSE=COURSES_ID
LEFT JOIN
	SEC_STATUSES ON
	COURSE_SECTIONS.COURSE_SECTIONS_ID=SEC_STATUSES.COURSE_SECTIONS_ID
LEFT JOIN
	STC_STATUSES ON
	STUDENT_COURSE_SEC.SCS_STUDENT_ACAD_CRED=STC_STATUSES.STUDENT_ACAD_CRED_ID
LEFT JOIN
	STUDENT_ACAD_CRED ON
	SCS_STUDENT_ACAD_CRED=STUDENT_ACAD_CRED.STUDENT_ACAD_CRED_ID
LEFT JOIN 
	SEC_DEPARTMENTS ON 
	COURSE_SECTIONS.COURSE_SECTIONS_ID=SEC_DEPARTMENTS.COURSE_SECTIONS_ID AND SEC_DEPT_PCTS > 0 
WHERE
	SEC_STATUSES.POS=1 AND SEC_STATUS='A'
	AND STC_STATUSES.POS=1 AND STC_STATUS IN ('N', 'A')
	AND 
	(GETDATE() < STC_END_DATE
	OR
	(STC_END_DATE IS NULL AND DATEDIFF(dd, STC_START_DATE, getdate())<=365)
	)
	AND NOT SEC_CRED_TYPE IN ('AB', 'VB', 'VBW', 'CS', 'G')
	AND NOT SEC_NAME LIKE ('%SUF%')
	AND NOT SEC_NAME LIKE ('%GRD%')