DECLARE @startDate DATE SET @startDate = DATEADD(day, -2, GETDATE())
DECLARE @endDate DATE SET @endDate = DATEADD(day, -1, GETDATE())

SELECT DISTINCT
	SEC_NAME
        ,CAST(SEC_SHORT_TITLE AS VARCHAR(MAX)) AS 'SEC_SHORT_TITLE'
	,SEC_START_DATE 'FROMDATE'
	,SEC_END_DATE 'TODATE'
        ,SEC_TERM
        ,COURSE_SECTIONS_CHGDATE
FROM
	COURSE_SECTIONS
LEFT JOIN
	COURSES ON 
	SEC_COURSE=COURSES_ID
LEFT JOIN
	SEC_STATUSES ON
	COURSE_SECTIONS.COURSE_SECTIONS_ID=SEC_STATUSES.COURSE_SECTIONS_ID
WHERE
	SEC_STATUSES.POS=1 AND SEC_STATUS='A'
	AND 
	(GETDATE() < SEC_END_DATE
	OR
	(SEC_END_DATE IS NULL AND DATEDIFF(dd, SEC_START_DATE, getdate())<=365)
	)
	AND NOT SEC_CRED_TYPE IN ('AB', 'VB', 'VBW', 'CS', 'G')
	AND NOT SEC_NAME LIKE ('%SUF%')
	AND NOT SEC_NAME LIKE ('%GRD%')