--Staff report

SELECT
	ID
	,FIRST_NAME, LAST_NAME 
	,POSITION.POS_TITLE
	,HRP_EFFECT_EMPLOY_DATE AS 'startDate'
	,POS_CLASS
	,DEPTS_DESC
	,POS_TYPE
	,CASE WHEN (
		POS_TITLE LIKE ('%Retired%')
		OR POS_TITLE LIKE ('%Layoff%')
		OR POS_TITLE LIKE ('%Resignation%')
		OR POS_TITLE LIKE ('%Unpaid%')
	) THEN 'INACTIVE' ELSE 'ACTIVE' END AS 'Status'
	,PERSTAT_END_DATE
	,PERSTAT_END_REASON
FROM
	HRPER
LEFT JOIN
	PERSON ON
	HRPER.HRPER_ID=PERSON.ID
LEFT JOIN
	PERSTAT ON
	HRPER_ID=PERSTAT_HRP_ID
LEFT JOIN
	POSITION ON
	PERSTAT.PERSTAT_PRIMARY_POS_ID=POSITION.POSITION_ID
LEFT JOIN
	DEPTS ON
	POS_DEPT=DEPTS_ID
WHERE
	(PERSTAT_END_REASON IS NULL OR DATEDIFF(dd, PERSTAT_END_DATE, GETDATE()) BETWEEN 0 AND 15)
	AND (PERSTAT_END_DATE IS NULL OR NOT DATEDIFF(dd, PERSTAT_END_DATE, GETDATE()) > 30)
	AND NOT (
		(
		POS_TITLE LIKE ('%Retired%')
		OR POS_TITLE LIKE ('Layoff%')
		OR POS_TITLE LIKE ('%Resignation%')
		OR POS_TITLE LIKE ('%Unpaid%')
		)
		AND 
		DATEDIFF(dd, PERSTAT_START_DATE, GETDATE()) >= 15
		AND
		PERSTAT_END_DATE IS NULL
	)
		