SELECT

	query.ID
	,FIRST_NAME
	,LAST_NAME
	,LOWER(CONCAT(LEFT(FIRST_NAME, 1), LEFT(LAST_NAME, 4), RIGHT(query.ID, 3))) AS 'newUsername'
	,BLDG_DESC
	,room 'RMAS_ROOM'
	,MIN(RMAS_START_DATE) AS 'startDate'
	,MAX(RMAS_END_DATE) AS 'endDate'
	,[empStatus]
	--,case when min(RMAS_START_DATE) > Getdate() then 'future' else 'current' end as 'stayStatus'

FROM

(
SELECT 
	PERSON.ID
	,FIRST_NAME
	,LAST_NAME
	,CONCAT(LEFT(FIRST_NAME, 1), LEFT(LAST_NAME, 4), RIGHT(PERSON.ID, 3)) AS 'newUsername'
	,BLDG_DESC
	,room
	,RMAS_START_DATE
	,RMAS_END_DATE
	,CASE WHEN PERSON.ID IN (
		SELECT
			HRPER_ID
		FROM
			HRPER
	) THEN 'e' ELSE 's' END AS 'empStatus'

FROM 
	RMAS_STATUSES
LEFT JOIN
	ROOM_ASSIGNMENT ON 
	RMAS_STATUSES.ROOM_ASSIGNMENT_ID=ROOM_ASSIGNMENT.ROOM_ASSIGNMENT_ID
LEFT JOIN
	(
	SELECT
		*
	FROM
		(
		SELECT
			RMAS_PERSON_ID AS 'secondaryID'
			,RMAS_ROOM 'room'
			,RMAS_START_DATE 'secondaryStart'
			,RMAS_END_DATE 'secondaryEnd'
			,ROW_NUMBER() OVER (PARTITION BY RMAS_PERSON_ID ORDER BY RMAS_START_DATE) AS 'rn'
		FROM
			RMAS_STATUSES
		LEFT JOIN
			ROOM_ASSIGNMENT ON
			RMAS_STATUSES.ROOM_ASSIGNMENT_ID=ROOM_ASSIGNMENT.ROOM_ASSIGNMENT_ID
		WHERE
			RMAS_END_DATE >= GETDATE() AND RMAS_STATUSES.POS=1 AND RMAS_STATUS='A'
		) testQuery
	WHERE
		testQuery.rn=1
	) secondaryAssignment ON
	ROOM_ASSIGNMENT.RMAS_PERSON_ID=secondaryAssignment.secondaryID
LEFT JOIN
	PERSON ON
	ROOM_ASSIGNMENT.RMAS_PERSON_ID=PERSON.ID
LEFT JOIN
	BUILDINGS ON 
	RMAS_BLDG=BUILDINGS.BUILDINGS_ID
WHERE
	(
	RMAS_END_DATE >= GETDATE()
	OR (ROOM_ASSIGNMENT_CHGDATE BETWEEN GETDATE()-1 AND GETDATE() AND RMAS_START_DATE <= GETDATE() )
	)
	AND RMAS_STATUSES.POS=1
	AND RMAS_STATUS='A'
) query 

GROUP BY
	query.ID
	,FIRST_NAME
	,LAST_NAME
	,[newUsername]
	,BLDG_DESC
	,room
	,[empStatus]